replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix

fullnameOverride: ""
nameOverride: ""
autoscaling:
  enabled: false  # Set to true if you want HorizontalPodAutoscaler (HPA) enabled
